# Generated by Django 3.1.3 on 2020-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201203_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person_who_asked',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
