# Generated by Django 3.1.3 on 2020-12-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201203_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='person_who_asked',
        ),
    ]
