# Generated by Django 3.1.3 on 2020-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_person_who_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='person_who_asked',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
